language: scala
scala:
- 2.11.5
jdk:
- oraclejdk8
sudo: false
script:

curl https://bintray.com/artifact/download/magnetic-io/vamp/io/vamp/pulse-api_2.11/0.7.0-RC3.dev-16/pulse-api_2.11-0.7.0-RC3.dev-16.jar
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- sbt coveralls
notifications:
  slack:
    secure: PtU8WrGwOkhyzaSlfUC+JkSZbwkhNQYFll4gWYueSxjC2EXCSo3GyWoZs3jlCmjVIhyiA32Wh/BduuGH6CUNbjqx+DQH+WYAgsO2/u2NtRPT87wP0DY0X9c7+OBIKZfnCsfIgWlYSrW3WKjiOFAZvu40ihgV/3ZUADF0n5UyUss=
