language: scala
scala:
- 2.11.5
jdk:
- oraclejdk8
sudo: false
install:
- sh "$TRAVIS_BUILD_DIR/.travis-ci-bintray-credentials.sh"
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test
- find $HOME/.sbt -name "*.lock" | xargs rm
after_success:
- sbt coveralls
- test ${TRAVIS_PULL_REQUEST} == "false" && test ${TRAVIS_BRANCH} == "master" &&
  sbt publish
notifications:
  slack:
    secure: PtU8WrGwOkhyzaSlfUC+JkSZbwkhNQYFll4gWYueSxjC2EXCSo3GyWoZs3jlCmjVIhyiA32Wh/BduuGH6CUNbjqx+DQH+WYAgsO2/u2NtRPT87wP0DY0X9c7+OBIKZfnCsfIgWlYSrW3WKjiOFAZvu40ihgV/3ZUADF0n5UyUss=
env:
  global:
  - secure: e6MAmhm9bnYMlJkhCgJHH5zermqHIN2rlbn+Quao2O2rCjwW2jeYATIvj912zwk0X7vZ7Cp3eBQUpRLxZW38ZkYbrPp6K84UKY8Fxz1aSUyg83GRqnEb4BbV5L5CDQC+u8P1Pb+MPU+3KQtrupQUse0xT9fa/+H0j4gi+DlFvVE=
  - secure: iRqr3ss34y81aqvQXpMzBErjdiSLZ5ggxRC9sLl9K2CtkWcxKlyYZmHql9gwgVNgJow8khqnlW4/Asr7XcSTw+bEq0PClM5li0huLLmDlCGtwsgMDfdEDTHtwKTTk98zS5UnhcBgbKIpEcLV0t8w0c3PDXNqxiK0KHdhYLlkiaE=
