language: scala
scala:
- 2.11.5
jdk:
- oraclejdk8
sudo: false
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test

after_success:
- sbt coveralls
notifications:
  slack:
    secure: PtU8WrGwOkhyzaSlfUC+JkSZbwkhNQYFll4gWYueSxjC2EXCSo3GyWoZs3jlCmjVIhyiA32Wh/BduuGH6CUNbjqx+DQH+WYAgsO2/u2NtRPT87wP0DY0X9c7+OBIKZfnCsfIgWlYSrW3WKjiOFAZvu40ihgV/3ZUADF0n5UyUss=
